Fix elements sticking out of the container, when there is not enough space
1uphealth/fhir-react pull request #236
Opened 2021-06-17 09:36 UTC by KonradNojman

Issue:  #235 

---

## Why are these changes needed?

When rendering fhir-react components 1 besides another, sometimes contents flows out of 1 component to another, when there is not enough space in the UI. The problem was found with the identifier name for the Coverage resource.

## What changed?

Added changes for multiple resources, that solve the problem of the contents sticking out. It is done by either using word-breaks to split the line into multiple ones if there is no space, or adding horizontal scrollbar e.g. for tables.

### Example screenshots:
|Before|After|
|--|--|
|Coverage: ![image](https://user-images.githubusercontent.com/60238331/122360049-61ce9e00-cf56-11eb-9858-ef90437d7009.png) |![image](https://user-images.githubusercontent.com/60238331/122360109-6e52f680-cf56-11eb-88d2-3f9b0e64d514.png)|
|Explanation of Benefit: ![image](https://user-images.githubusercontent.com/60238331/122360389-a9552a00-cf56-11eb-8dea-95d688da3d0b.png)|![image](https://user-images.githubusercontent.com/60238331/122360474-b5d98280-cf56-11eb-9727-e89428447db4.png)|

## How are these changes tested?

- Checked visually every component for different screen resolutions
- All tests are still passing

2021-06-17 11:07 UTC, kyle1uphealth approved these changes
LGTM

2021-06-18 08:40 UTC, ctomasz requested changes
overall look good, but I left one comment - would you consider it?

2021-06-18 08:40 UTC, ctomasz commented on .circleci/config.yml
> +              echo "Available here: http://storybook-fhir-react-lib.s3-website-us-east-1.amazonaws.com/dev/${CIRCLE_BRANCH}"
do we need a storybook instance for each branch? 
how/who this will cleanup once branch will be merged?

2021-06-18 09:06 UTC, ctomasz approved these changes

2021-06-18 09:08 UTC, merged