Add/Update the FHIR resource component - Condition
1uphealth/fhir-react pull request #274
Opened 2021-10-21 06:12 UTC by btmikolajczyk

Issue:  [#9](https://app.zenhub.com/workspaces/patient-app-6140de7e31081800158d8ecf/issues/1uphealth/patient/9)

---

##### PR Checklist
- [X] Give this PR a meaningful title
- [X] Add a link to the related issue at the top of this description (above)
- [ ] Connect this PR with the related issue via ZenHub with the button below this text box (or at the bottom of the page after the PR is created)
- [X] Ensure your branch is up to date with the target branch and resolve any conflicts
- [X] Answer the below questions to describe your PR for reviewers
- [X] Request at least two reviewers using the "Reviewers" section on the right, usually including at least one reviewer from your team
- [ ] Notify the requested reviewers in the #code-review Slack channel once the PR is ready for review

---

## Why are these changes needed?
The changes made are caused by the main goal of our task, which is to change the style of the elements of the FHIR library. In this PR, the component responsible for the condition resource has been modified.

## What changed?
As part of the changes to the condition component, the way the component is presented has been changed. Now component uses the previously added Accordion container. Also added fixes to the header related to the positioning of its elements. When a component is in a collapsed state, it only displays generic condition resource data. When clicked by the user, it enters the show state, in which it displays all the data that was transmitted to it. 
![Screenshot 2021-10-21 at 08 02 51](https://user-images.githubusercontent.com/81750836/138220487-34e2327b-eb3f-4974-b0e2-4a171fc9d098.png)
![Screenshot 2021-10-21 at 08 03 02](https://user-images.githubusercontent.com/81750836/138220489-63f1ce3f-d706-4949-9647-32901f7bd560.png)

## How are these changes tested?
Changes were tested with storybook. Here is the link to the storybook deployed for this PR: [storybook]()

2021-11-02 06:59 UTC, pslawinski-htd commented on src/components/ui/index.js
> +          {props.upperRowContentRightSide || <div />}
Will it be possible that if props are missing we will end up with two closing tags?

2021-11-16 06:42 UTC, sflejszman requested changes

2021-11-16 06:42 UTC, sflejszman commented on src/components/resources/Condition/Condition.js
> +                <Title>{codeText || ''}</Title>
Can we set default value here -> https://github.com/1uphealth/fhir-react/pull/274/files#diff-0373f8d952ede9b208713269db64604129f1ce8777d278ce0aa1123e4d6ef1cbR16

2021-11-16 06:42 UTC, sflejszman commented on src/components/resources/Immunization/Immunization.js
> +          {_get(doseQuantity, 'value')} &nbsp;
What do you think about using join instead of &nbsp;?

2021-11-16 06:42 UTC, sflejszman commented on src/components/resources/Procedure/Procedure.js
> +                    {'performed   '}
Too much spacing?

2021-11-16 06:42 UTC, sflejszman commented on src/components/resources/Procedure/Procedure.js
> +                    {'   to   '}
What do you think about using here margin to set more space between elements?

2021-11-16 06:42 UTC, sflejszman commented on src/components/ui/index.js
> +      props.children
What do you think about changing ternary operator to ||

2021-11-16 12:35 UTC, btmikolajczyk commented on src/components/resources/Procedure/Procedure.js
> +                    {'performed   '}
I solved it here [PR#277](https://github.com/1uphealth/fhir-react/pull/277/files#diff-f921de35acc0a2549d2b0c6c5815b7bea141a801f793fcdbdf288e6cf1377d27R110)

2021-11-16 12:35 UTC, btmikolajczyk commented on src/components/resources/Procedure/Procedure.js
> +                    {'   to   '}
I solved it here [PR#277](https://github.com/1uphealth/fhir-react/pull/277/files#diff-f921de35acc0a2549d2b0c6c5815b7bea141a801f793fcdbdf288e6cf1377d27R110)

2021-11-16 13:41 UTC, sflejszman approved these changes

2021-11-16 13:47 UTC, pslawinski-htd approved these changes

2021-11-16 13:48 UTC, merged

2021-11-16 13:54 UTC, btmikolajczyk commented
Reopen PR

2021-11-16 14:49 UTC, btmikolajczyk commented
Hi @tim1uphealth and @liam1uphealth I accidentally merged this PR, but the changes made to it were in PR 277, which was already approved by Tim.