Practitioner resource
1uphealth/fhir-react pull request #275
Opened 2021-10-27 09:49 UTC by pslawinski-htd

Issue:  [Add FHIR Resource: Practitioner](https://app.zenhub.com/workspaces/patient-app-6140de7e31081800158d8ecf/issues/1uphealth/patient/8)

---

##### PR Checklist
- [x] Give this PR a meaningful title
- [x] Add a link to the related issue at the top of this description (above)
- [x] Connect this PR with the related issue via ZenHub with the button below this text box (or at the bottom of the page after the PR is created)
- [x] Ensure your branch is up to date with the target branch and resolve any conflicts
- [x] Answer the below questions to describe your PR for reviewers
- [x] Request at least two reviewers using the "Reviewers" section on the right, usually including at least one reviewer from your team
- [x] Notify the requested reviewers in the #code-review Slack channel once the PR is ready for review

---

## Why are these changes needed?

Practitioner resource styling has been revamped.

## What changed?

<img width="447" alt="Zrzut ekranu 2021-10-27 o 16 34 12" src="https://user-images.githubusercontent.com/79844092/139087401-9a073dd6-8ece-4485-aa47-9ed7d7957955.png">

## How are these changes tested?

Unit tests were updated to facilitate revamped resource. Storybook was used to test the resource visually.
Deployed storybook is available here: [link](http://fhir-react-lib-test-storybook.s3-website-us-east-1.amazonaws.com/branch/practitioner-resource/?path=/story/practitioner--default-visualization-dstu-2).

2021-11-15 15:35 UTC, sflejszman requested changes

2021-11-15 15:35 UTC, sflejszman commented on src/components/resources/Condition/Condition.js
> +                <Title>{codeText || ''}</Title>
Can we set default value in destructuring?

2021-11-15 15:35 UTC, sflejszman commented on src/components/resources/Procedure/Procedure.js
> +                    {'   to   '}
Can we set space between elements using margin?

2021-11-15 15:35 UTC, sflejszman commented on src/components/ui/index.js
> +    {// TODO comment why children
To do?

2021-11-15 15:35 UTC, sflejszman commented on src/components/ui/index.js
> +    props.children ? (
What do you think about use in this place:`props.children ||`

2021-11-17 09:31 UTC, sflejszman approved these changes
🚀

2021-11-22 17:02 UTC, liam1uphealth approved these changes
lgtm

2021-11-24 06:24 UTC, merged