Create FHIR resource: ResourceCategory component
1uphealth/fhir-react pull request #280
Opened 2021-11-10 11:37 UTC by michal-maksajda

Issue:  #279 

---

##### PR Checklist
- [x] Give this PR a meaningful title
- [x] Add a link to the related issue at the top of this description (above)
- [x] Connect this PR with the related issue via ZenHub with the button below this text box (or at the bottom of the page after the PR is created)
- [x] Ensure your branch is up to date with the target branch and resolve any conflicts
- [x] Answer the below questions to describe your PR for reviewers
- [x] Request at least two reviewers using the "Reviewers" section on the right, usually including at least one reviewer from your team
- [x] Notify the requested reviewers in the #code-review Slack channel once the PR is ready for review

---

## Why are these changes needed?

Due to the latest redesign, which introduced bootstrapped version of UI components, creating ResourceCategory was necessary to fulfill the requirements.

## What changed?

The ResourceCategory component has been created. Title & HeaderIcon components were used as the nested parts of the main component.
<img width="689" alt="Zrzut ekranu 2021-11-10 o 11 16 07" src="https://user-images.githubusercontent.com/86961707/141094808-22fe33c0-a975-4306-be39-1d57fada7545.png">

## How are these changes tested?

- All automatic tests are passing
- The ResourceCategory component might be tested manually by viewing the current version of deployed [storybook](https://fhir-react-lib-test-storybook.s3.amazonaws.com/branch/add-FHIR-resource-resourcecategory/index.html?path=/story/resourcecategory--example-without-items-count)

2021-11-15 15:22 UTC, sflejszman requested changes
Great work 🚀  I left some suggestions ;)

2021-11-15 15:22 UTC, sflejszman commented on src/components/resources/ResourceCategory/ResourceCategory.js
> +                {itemsCount} {Number(itemsCount) === 1 ? 'item' : 'items'}
What do you think about creating a function to pluralize words?

2021-11-15 15:22 UTC, sflejszman commented on src/components/resources/ResourceCategory/ResourceCategory.js
> +          {isPositiveNumber(itemsCount) && (
```suggestion
          {itemsCount > 0 && (
```

2021-11-15 15:22 UTC, sflejszman commented on src/components/resources/ResourceCategory/ResourceCategory.js
> +          {isPositiveNumber(itemsCount) && (
Of course, before we need to parse the string to number

2021-11-15 15:22 UTC, sflejszman commented on src/assets/containers/ResourceCategory/chevron-right.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
What do you think about creating the chevron icon as a common asset?

2021-11-16 08:21 UTC, pslawinski-htd requested changes

2021-11-16 08:21 UTC, pslawinski-htd commented on src/components/resources/ResourceCategory/ResourceCategory.test.js
> +  });
Let's also test against icorrect source data (`itemsCount: -1 // or 0 or 'asdf'`)

2021-11-18 07:20 UTC, pslawinski-htd approved these changes

2021-11-18 07:45 UTC, sflejszman approved these changes
🚀

2021-11-23 15:19 UTC, beck1uphealth commented
Is anything supposed to happen when you click? When I try in storybook, nothing happens

2021-11-23 16:12 UTC, liam1uphealth commented
@beck1uphealth it should link to https://fhir-react-lib-test-storybook.s3.amazonaws.com/branch/add-FHIR-resource-resourcecategory/index.html?path=/story/resourcecategory--example-without-items-count

2021-11-23 16:27 UTC, beck1uphealth commented
@liam1uphealth Yeah, I am able to see the storybook, I was wondering if when you click on the resource component in the storybook if it should do anything since it is a button. I see the different ones that say 1 item and 41 items, but I was expecting it to do something when I clicked it

2021-11-23 19:41 UTC, michal-maksajda commented
Hi. This ResourceCategory component is a template of the button. We should be able to pass items count as a property, for this reason, there are different variants listed in a storybook. Currently, the button has no onClick behaviour specified.

2021-11-23 19:43 UTC, beck1uphealth approved these changes

2021-11-24 06:32 UTC, merged