Update Appointment component - FHIR next
1uphealth/fhir-react pull request #285
Opened 2021-11-19 11:06 UTC by sflejszman

Issue:  [ZH-15](https://app.zenhub.com/workspaces/patient-app-6140de7e31081800158d8ecf/issues/1uphealth/patient/15)

---

##### PR Checklist
- [x] Give this PR a meaningful title
- [x] Add a link to the related issue at the top of this description (above)
- [ ] Connect this PR with the related issue via ZenHub with the button below this text box (or at the bottom of the page after the PR is created)
- [x] Ensure your branch is up to date with the target branch and resolve any conflicts
- [x] Answer the below questions to describe your PR for reviewers
- [ ] Request at least two reviewers using the "Reviewers" section on the right, usually including at least one reviewer from your team
- [ ] Notify the requested reviewers in the #code-review Slack channel once the PR is ready for review

---

## Why are these changes needed?
in progress

## What changed?
in progress

## How are these changes tested?

2021-11-22 07:22 UTC, michal-maksajda commented on src/components/ui/index.js
> +        'text-nowrap'} text-muted text-gray-500`}
My suggestion is to keep only one text style property. The other one here has no effect.

2021-11-22 08:39 UTC, michal-maksajda approved these changes
👍

2021-11-22 16:54 UTC, liam1uphealth requested changes
going to block this until the responsive issues are addressed.

2021-11-22 16:54 UTC, liam1uphealth commented on src/style.scss
> +  width: 130px;
this may be the cause for this component not being responsive. 
![image](https://user-images.githubusercontent.com/54856814/142902049-a873940a-01a5-4d5a-8792-03d8fb353741.png)

2021-11-23 13:57 UTC, sflejszman commented on src/style.scss
> +  width: 130px;
Done 👍 
<img width="1707" alt="Screenshot 2021-11-23 at 14 57 23" src="https://user-images.githubusercontent.com/12885723/143037423-95745f58-cd49-4abf-b104-2adbfb6d17a4.png">

2021-11-24 06:32 UTC, jaceksanko approved these changes
👍

2021-11-29 18:35 UTC, glenn1uphealth approved these changes

2021-11-30 07:28 UTC, merged