Update patient component - FHIR next
1uphealth/fhir-react pull request #290
Opened 2021-11-24 11:59 UTC by sflejszman

Issue:  [ZH-6](https://app.zenhub.com/workspaces/patient-app-6140de7e31081800158d8ecf/issues/1uphealth/patient/6)

---

##### PR Checklist
- [x] Give this PR a meaningful title
- [x] Add a link to the related issue at the top of this description (above)
- [x] Connect this PR with the related issue via ZenHub with the button below this text box (or at the bottom of the page after the PR is created)
- [x] Ensure your branch is up to date with the target branch and resolve any conflicts
- [x] Answer the below questions to describe your PR for reviewers
- [x] Request at least two reviewers using the "Reviewers" section on the right, usually including at least one reviewer from your team
- [x] Notify the requested reviewers in the #code-review Slack channel once the PR is ready for review

---

## Why are these changes needed?

Update styles for Patient according to designs in FIGMA.

## What changed?

- install missing libs,
- merge fhir-react-next branch
- update styles and remove unused elements,
- add accordion to component
- remove unused files
- update header component

## Screenshot:
<img width="1791" alt="Screenshot 2021-11-24 at 12 54 46" src="https://user-images.githubusercontent.com/12885723/143233871-de4620c5-abdd-4cfb-b931-a126136b4669.png">

## How are these changes tested?

- All automatic tests are passing
- The ResourceCategory component might be tested manually by viewing the current version of deployed [storybook](https://fhir-react-lib-test-storybook.s3.amazonaws.com/branch/update-patient-component/index.html?path=/story/patient--default-visualization-dstu-2)

2021-11-26 12:19 UTC, jaceksanko approved these changes
💯

2021-11-30 19:19 UTC, glenn1uphealth requested changes
Two columns for body content for mobile devices results in data wrapping in narrow column.

Telephone                       213 555-
                                         1212
                                         212 555-
                                         1313

 I suggest a single column for labels and data:

Telephone
212-555-1212
212-555-1313

2021-12-01 08:25 UTC, sflejszman commented
@glenn1uphealth Ready for re-check.
<img width="673" alt="Screenshot 2021-12-01 at 09 18 03" src="https://user-images.githubusercontent.com/12885723/144198386-79257770-f7e1-4363-b195-d4ebe6f4f359.png">

2021-12-01 17:09 UTC, glenn1uphealth approved these changes

2021-12-02 06:37 UTC, merged