FHIR React Next
1uphealth/fhir-react pull request #295
Opened 2021-12-09 16:30 UTC by tony1uphealth

Issue:  

---

##### PR Checklist
- [ ] Give this PR a meaningful title
- [ ] Add a link to the related issue at the top of this description (above)
- [ ] Connect this PR with the related issue via ZenHub with the button below this text box (or at the bottom of the page after the PR is created)
- [ ] Ensure your branch is up to date with the target branch and resolve any conflicts
- [ ] Answer the below questions to describe your PR for reviewers
- [ ] Request at least two reviewers using the "Reviewers" section on the right, usually including at least one reviewer from your team
- [ ] Notify the requested reviewers in the #code-review Slack channel once the PR is ready for review

---

## Why are these changes needed?

## What changed?

## How are these changes tested?

2021-12-09 17:39 UTC, liam1uphealth approved these changes

2021-12-09 19:22 UTC, glenn1uphealth requested changes
New Condition resource has mobile formatting issues. I see also that this PR was not reviewed by 1Up Engineer.
https://github.com/1uphealth/fhir-react/pull/274

 Please correct header formatting issues shown below:
![DefVisDSTU2](https://user-images.githubusercontent.com/94016325/145458701-e7892768-6262-40b8-a735-1c36bc7e1b10.jpg)
![ExWithSevSTU3](https://user-images.githubusercontent.com/94016325/145458730-6ca96822-7563-44ee-8958-9e8c67e4cd3c.jpg)
![Ex3OfDSTU2](https://user-images.githubusercontent.com/94016325/145458757-d70f9d4d-111e-4aaf-9de9-df1835a9c6f9.jpg)

2021-12-09 20:15 UTC, tony1uphealth commented on package.json
> +  "version": "0.3.0",
This change isn't reflected in the checked-in `package-lock.json`. Please run `npm i` and check in the changes to `package-lock.json`

2021-12-09 20:20 UTC, tony1uphealth commented on package.json
> +  "version": "0.3.0",
Done :)

2021-12-10 09:11 UTC, jaceksanko commented
@glenn1uphealth  I corrected the second badge and dates at the mobile view:
<img width="325" alt="Zrzut ekranu 2021-12-10 o 10 06 24" src="https://user-images.githubusercontent.com/35079921/145547950-e752f765-f5f8-405f-a1c8-f146d0642c9c.png">

2021-12-10 16:03 UTC, glenn1uphealth approved these changes

2021-12-13 20:08 UTC, merged