Fix sass loading & headerIcon condition (v0.3.2)
1uphealth/fhir-react pull request #299
Opened 2021-12-16 14:16 UTC by michal-maksajda

This PR includes:
- update of loaders properties in `webpack.config.js` file: 
   - `.scss` files are now also compiled into a single CSS file as the result
   - svg icons are being loaded by `svg-url-loader`
- fix of condition while displaying HeaderIcon component

2021-12-16 18:42 UTC, tony1uphealth requested changes
Some general feedback:

* No need to include Liam or me as a reviewer - enough to include Glenn and Beck and they can reach out if they need assistance reviewing
* Can you please include testing instructions in the PR description, and screenshots of before/after? Can help to think "what would someone new coming into this ticket need to know to see what I fixed?"

2021-12-16 19:13 UTC, michal-maksajda commented
@tony1uphealth Thank you for the response. The PR content has been updated.

2021-12-16 20:06 UTC, beck1uphealth approved these changes
Left one comment about the import change that seemed strange, otherwise it looks good!

2021-12-16 20:06 UTC, beck1uphealth commented on src/components/resources/ResourceCategory/ResourceCategory.js
> +            src={require('../../../assets/common/chevron-right.svg')}
Why did this change from an import to an inline require?

2021-12-16 21:15 UTC, michal-maksajda commented on src/components/resources/ResourceCategory/ResourceCategory.js
> +            src={require('../../../assets/common/chevron-right.svg')}
This change in ResourceCategory was made to adjust the SVG obtaining implementation to be compatible with `svg-loader` and to follow the convention set for SVG icons e.g. in fixtures file with other SVG's.

2021-12-17 11:34 UTC, jaceksanko commented
Maybe we should link a current version of the storybook to the badge storybook at readme file?

2021-12-17 12:14 UTC, jaceksanko approved these changes
👍

2021-12-20 14:30 UTC, tony1uphealth approved these changes

2021-12-23 14:03 UTC, merged