[PATIENT-1] fixed datePeriod display; fixed supportingInfo display
1uphealth/fhir-react pull request #301
Opened 2021-12-29 22:13 UTC by christopher1uphealth

Issue:  

---

##### PR Checklist
- [ ] Give this PR a meaningful title
- [ ] Add a link to the related issue at the top of this description (above)
- [ ] Connect this PR with the related issue via ZenHub with the button below this text box (or at the bottom of the page after the PR is created)
- [ ] Ensure your branch is up to date with the target branch and resolve any conflicts
- [ ] Answer the below questions to describe your PR for reviewers
- [ ] Request at least two reviewers using the "Reviewers" section on the right, usually including at least one reviewer from your team
- [ ] Notify the requested reviewers in the #code-review Slack channel once the PR is ready for review

---

## Why are these changes needed?

## What changed?

## How are these changes tested?

2021-12-29 23:31 UTC, glenn1uphealth reviewed
I don't see any changes to test files. How was this tested?

2021-12-30 17:50 UTC, glenn1uphealth submitted a review, later dismissed
Please identify code base(s) for patient app this where this will be applied. e.g. - Internal/Apps/provider or Patient repositories.

2021-12-30 17:55 UTC, glenn1uphealth requested changes
Please show code base where this will be deployed - e.g. - existing patient app or new patient app

2022-01-03 15:16 UTC, sflejszman requested changes

2022-01-03 15:16 UTC, sflejszman commented on src/components/resources/ExplanationOfBenefit/ExplanationOfBenefit.js
> +                            {serviceItem.servicedDate ||
Please don't use the nested ternary operator

2022-01-03 15:16 UTC, sflejszman commented on src/components/resources/ExplanationOfBenefit/ExplanationOfBenefit.js
> +                              infoKey === 'timingDate' ? (
What do you think about creating condition based on component, it will be look like:
`const StatusComponent = infoKey=== 'timingDate' ? Date : Coding`, than you can use it like:
`<StatusComponent fhirData={infoStatus} />`

2022-01-04 17:38 UTC, christopher1uphealth commented on src/components/resources/ExplanationOfBenefit/ExplanationOfBenefit.js
> +                              infoKey === 'timingDate' ? (
👍🏻

2022-01-04 17:38 UTC, christopher1uphealth commented on src/components/resources/ExplanationOfBenefit/ExplanationOfBenefit.js
> +                            {serviceItem.servicedDate ||
👍🏻

2022-01-05 09:52 UTC, sflejszman approved these changes

2022-01-05 09:53 UTC, sflejszman commented
Please fix linter issue 🙏

2022-01-07 19:53 UTC, Roger1uphealth approved these changes
I ran storybook with your changes and everything looks good to me.

2022-01-10 20:57 UTC, Roger1uphealth commented
> Please show code base where this will be deployed - e.g. - existing patient app or new patient app

Vikas confirmed during standup last week that the codebase for the current production patient app(https://app.1up.health/patient) lives in the apps/provider directory in the 1uphealth/internal repo.  @Khristina1UpHealth also confirmed that this change can be applied to the existing patient app.

With that said, @glenn1uphealth, @christopher1uphealth are there additional changes needed in order to get this change applied to the existing patient app?

2022-01-11 16:32 UTC, christopher1uphealth commented
I think Glenn needs to change his approval from requested changes to approved and then I can merge and publish the library.

2022-01-25 23:01 UTC, glenn1uphealth approved these changes

2022-01-26 14:08 UTC, merged